import type { AiProviderConfig } from "./aiConfigTypes";

const capabilities = {
  streaming: "supported",
  toolCalling: "supported",
  structuredOutput: "supported",
  reasoning: "untested",
} as const;

const createdAt = "2026-07-31T06:00:00.000Z";

export const PROTOTYPE_AI_PROVIDERS: AiProviderConfig[] = [
  {
    id: "ai-claude",
    providerKind: "anthropic",
    name: "Claude Sonnet 5",
    baseUrl: "https://api.anthropic.com",
    modelId: "claude-sonnet-5",
    credentialConfigured: true,
    credentialHint: "sk-••••••••EVPN",
    isDefault: false,
    connectionStatus: "connected",
    latencyMs: 412,
    testedAt: "2026-07-31T07:58:00.000Z",
    capabilities,
    createdAt,
    updatedAt: "2026-07-31T07:58:00.000Z",
  },
  {
    id: "ai-openai",
    providerKind: "openai",
    name: "GPT-4o",
    baseUrl: "https://api.openai.com/v1",
    modelId: "gpt-4o",
    credentialConfigured: true,
    credentialHint: "sk-••••••••X7K2",
    isDefault: false,
    connectionStatus: "connected",
    latencyMs: 689,
    testedAt: "2026-07-31T07:55:00.000Z",
    capabilities,
    createdAt,
    updatedAt: "2026-07-31T07:55:00.000Z",
  },
  {
    id: "ai-deepseek",
    providerKind: "deepseek",
    name: "DeepSeek V3",
    baseUrl: "https://api.deepseek.com/v1",
    modelId: "deepseek-chat",
    credentialConfigured: true,
    credentialHint: "sk-••••••••9MQA",
    isDefault: false,
    connectionStatus: "connected",
    latencyMs: 1024,
    testedAt: "2026-07-31T07:48:00.000Z",
    capabilities,
    createdAt,
    updatedAt: "2026-07-31T07:48:00.000Z",
  },
  {
    id: "ai-kimi",
    providerKind: "kimi",
    name: "Kimi K2",
    baseUrl: "https://api.moonshot.cn/v1",
    modelId: "kimi-k2",
    credentialConfigured: true,
    credentialHint: "sk-••••••••H4ZR",
    isDefault: false,
    connectionStatus: "failed",
    testedAt: "2026-07-31T07:00:00.000Z",
    testError: "The provider rejected the saved credential.",
    capabilities: {
      streaming: "untested",
      toolCalling: "untested",
      structuredOutput: "untested",
      reasoning: "untested",
    },
    createdAt,
    updatedAt: "2026-07-31T07:00:00.000Z",
  },
  {
    id: "ai-ollama",
    providerKind: "ollama",
    name: "Llama 3.1 (local)",
    baseUrl: "http://127.0.0.1:11434/v1",
    modelId: "llama3.1:70b",
    credentialConfigured: false,
    isDefault: false,
    connectionStatus: "connected",
    latencyMs: 53,
    testedAt: "2026-07-31T08:00:00.000Z",
    capabilities,
    createdAt,
    updatedAt: "2026-07-31T08:00:00.000Z",
  },
];
