import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const root = process.cwd();

describe("desktop updater configuration", () => {
  it("uses the GitHub publish metadata generated by electron-builder", () => {
    const packageJson = JSON.parse(
      readFileSync(`${root}/package.json`, "utf8"),
    ) as {
      build?: {
        publish?: {
          provider?: string;
          owner?: string;
          repo?: string;
        };
      };
    };
    const mainProcess = readFileSync(`${root}/electron/main.cts`, "utf8");

    expect(packageJson.build?.publish).toEqual({
      provider: "github",
      owner: "foooag",
      repo: "Buzz",
    });
    expect(mainProcess).not.toContain("setFeedURL");
  });
});
