export const COMMAND_NAMES = [
  "app_health",
  "ai_list_provider_configs",
  "ai_create_provider_config",
  "ai_update_provider_config",
  "ai_delete_provider_config",
  "ai_test_provider_config",
  "ai_probe_provider_config",
  "ai_agent_create",
  "ai_agent_prompt",
  "ai_agent_steer",
  "ai_agent_abort",
  "ai_agent_decide_tool",
  "ai_agent_close",
  "ai_list_sessions",
  "ai_load_session",
  "ai_rename_session",
  "ai_delete_session",
  "agent_create",
  "agent_prompt",
  "agent_steer",
  "agent_abort",
  "agent_decide_tool",
  "agent_close",
  "inventory_list_vaults",
  "inventory_create_vault",
  "inventory_update_vault",
  "inventory_delete_vault",
  "inventory_list_groups",
  "inventory_create_group",
  "inventory_list_hosts",
  "inventory_create_host",
  "inventory_update_host",
  "inventory_delete_host",
  "inventory_list_identities",
  "inventory_create_identity",
  "inventory_update_identity",
  "inventory_delete_identity",
  "ssh_store_credential",
  "ssh_open",
  "ssh_decide_host_key",
  "ssh_reconnect",
  "ssh_list_known_hosts",
  "ssh_delete_known_host",
  "port_forward_start",
  "port_forward_decide_host_key",
  "port_forward_stop",
  "port_forward_list_active",
  "port_forward_list_rules",
  "port_forward_create_rule",
  "port_forward_update_rule",
  "port_forward_delete_rule",
  "terminal_open",
  "terminal_write",
  "terminal_resize",
  "terminal_close",
  "sftp_open",
  "sftp_decide_host_key",
  "sftp_reconnect",
  "sftp_list_remote",
  "sftp_list_local",
  "sftp_enqueue_upload",
  "sftp_enqueue_download",
  "sftp_resolve_conflict",
  "sftp_cancel_transfer",
  "sftp_delete_remote",
  "sftp_rename_remote",
  "sftp_mkdir_remote",
  "sftp_open_with",
  "sftp_resolve_open_with_conflict",
  "sftp_close_open_with",
  "sftp_list_associations",
  "sftp_set_association",
  "sftp_delete_association",
  "sftp_close",
] as const;

export type CommandName = (typeof COMMAND_NAMES)[number];

const commandSet = new Set<string>(COMMAND_NAMES);

export function isCommandName(value: unknown): value is CommandName {
  return typeof value === "string" && commandSet.has(value);
}
