import { CaseSensitive } from "lucide-react";
import { useEffect, useState } from "react";

/**
 * A small overlay shown at the right edge of a password field while Caps Lock
 * is active, so case-sensitive credentials are not entered reversed. The
 * overlay is pointer-events-none so clicks still land on the input.
 *
 * Caps Lock state is only observable through KeyboardEvent#getModifierState
 * (the method does not exist on elements), so every keyup on the window is
 * re-read. Because a fresh KeyboardEvent always starts with modifiers unset,
 * only events actually generated by the user are trusted.
 */
export function CapsLockIndicator() {
  const [capsLock, setCapsLock] = useState(false);
  useEffect(() => {
    if (typeof window === "undefined") return;
    const check = (event?: KeyboardEvent) =>
      setCapsLock(Boolean(event?.getModifierState("CapsLock")));
    window.addEventListener("keyup", check);
    return () => window.removeEventListener("keyup", check);
  }, []);
  return (
    <span
      className={
        "pointer-events-none absolute right-2.5 top-1/2 -translate-y-1/2 " +
        (capsLock ? "text-coral-red" : "hidden text-fog/50")
      }
    >
      <CaseSensitive
        size={15}
        role="img"
        aria-label="Caps Lock is on"
        className="pointer-events-none"
      />
    </span>
  );
}
