// inventory.jsx — mock resource data for the broad-sweep Termius prototype.
// Vaults, groups, hosts, identities/keys, port-forward rules, history,
// SFTP filesystem, snippets, terminal themes, fonts, keyboard shortcuts,
// known hosts, file associations. Sanitized — no real hosts, users, or IPs.
// Exported to `window` as `INV`.

const VAULT = {
  id: "vault-local",
  name: "Local vault",
  kind: "local", // local | team
  status: "unlocked",
  counts: { hosts: 12, keys: 4, snippets: 8 },
};

const GROUPS = [
  { id: "g-prod", name: "Production", color: "coral", count: 4 },
  { id: "g-stage", name: "Staging", color: "teal", count: 2 },
  { id: "g-db", name: "Databases", color: "violet", count: 3 },
  { id: "g-edge", name: "Edge & Network", color: "lime", count: 3 },
];

// status: online | offline | connecting | failed
// protocol: ssh | telnet | serial
const HOSTS = [
  {
    id: "h-web-prod-01",
    name: "web-prod-01",
    group: "g-prod",
    protocol: "ssh",
    address: "10.0.0.10",
    port: 22,
    username: "ubuntu",
    identity: "deploy-ed25519",
    tags: ["web", "nginx", "shop"],
    status: "online",
    label: "Nginx · shop frontend",
    jumpHost: "bastion-jump",
    proxy: null,
    env: { NODE_ENV: "production", SHOP_ENV: "prod" },
    startupSnippets: ["s-tail-log", "s-status"],
    lastConnected: "2m ago",
  },
  {
    id: "h-web-prod-02",
    name: "web-prod-02",
    group: "g-prod",
    protocol: "ssh",
    address: "10.0.0.11",
    port: 22,
    username: "ubuntu",
    identity: "deploy-ed25519",
    tags: ["web", "nginx"],
    status: "online",
    label: "Nginx · shop frontend",
    jumpHost: "bastion-jump",
    proxy: null,
    env: {},
    startupSnippets: [],
    lastConnected: "1h ago",
  },
  {
    id: "h-api-prod-01",
    name: "api-prod-01",
    group: "g-prod",
    protocol: "ssh",
    address: "10.0.0.20",
    port: 22,
    username: "deploy",
    identity: "deploy-ed25519",
    tags: ["api", "gunicorn"],
    status: "offline",
    label: "Gunicorn API",
    jumpHost: "bastion-jump",
    proxy: null,
    env: {},
    startupSnippets: [],
    lastConnected: "3d ago",
  },
  {
    id: "h-jump-bastion",
    name: "bastion-jump",
    group: "g-prod",
    protocol: "ssh",
    address: "203.0.113.10",
    port: 2200,
    username: "bridge",
    identity: "bridge-ed25519",
    tags: ["bastion", "jump"],
    status: "online",
    label: "Bastion / jump host",
    jumpHost: null,
    proxy: null,
    env: {},
    startupSnippets: [],
    lastConnected: "just now",
  },
  {
    id: "h-db-primary",
    name: "db-primary",
    group: "g-db",
    protocol: "ssh",
    address: "10.0.2.5",
    port: 22,
    username: "postgres",
    identity: "db-rsa",
    tags: ["postgres", "primary"],
    status: "online",
    label: "Postgres primary",
    jumpHost: "bastion-jump",
    proxy: null,
    env: {},
    startupSnippets: ["s-pg-stat"],
    lastConnected: "12m ago",
  },
  {
    id: "h-db-replica-02",
    name: "db-replica-02",
    group: "g-db",
    protocol: "ssh",
    address: "10.0.2.6",
    port: 22,
    username: "postgres",
    identity: "db-rsa",
    tags: ["postgres", "replica"],
    status: "online",
    label: "Postgres replica",
    jumpHost: "bastion-jump",
    proxy: null,
    env: {},
    startupSnippets: [],
    lastConnected: "12m ago",
  },
  {
    id: "h-redis-cache-01",
    name: "redis-cache-01",
    group: "g-db",
    protocol: "ssh",
    address: "10.0.2.20",
    port: 22,
    username: "redis",
    identity: "deploy-ed25519",
    tags: ["redis", "cache"],
    status: "offline",
    label: "Redis cache",
    jumpHost: "bastion-jump",
    proxy: null,
    env: {},
    startupSnippets: [],
    lastConnected: "5d ago",
  },
  {
    id: "h-stage-app-01",
    name: "stage-app-01",
    group: "g-stage",
    protocol: "ssh",
    address: "10.0.4.10",
    port: 22,
    username: "ubuntu",
    identity: "deploy-ed25519",
    tags: ["web", "staging"],
    status: "online",
    label: "Staging frontend",
    jumpHost: "bastion-jump",
    proxy: null,
    env: { NODE_ENV: "staging" },
    startupSnippets: [],
    lastConnected: "yesterday",
  },
  {
    id: "h-stage-worker",
    name: "stage-worker",
    group: "g-stage",
    protocol: "ssh",
    address: "10.0.4.11",
    port: 22,
    username: "ubuntu",
    identity: "deploy-ed25519",
    tags: ["worker", "staging"],
    status: "offline",
    label: "Background worker",
    jumpHost: "bastion-jump",
    proxy: null,
    env: {},
    startupSnippets: [],
    lastConnected: "2d ago",
  },
  {
    id: "h-router-edge-01",
    name: "router-edge-01",
    group: "g-edge",
    protocol: "ssh",
    address: "10.0.7.1",
    port: 22,
    username: "admin",
    identity: "net-ed25519",
    tags: ["router", "edge"],
    status: "online",
    label: "Edge router",
    jumpHost: null,
    proxy: null,
    env: {},
    startupSnippets: [],
    lastConnected: "4h ago",
  },
  {
    id: "h-switch-core-01",
    name: "switch-core-01",
    group: "g-edge",
    protocol: "telnet",
    address: "10.0.7.2",
    port: 23,
    username: "admin",
    identity: null,
    tags: ["switch", "core"],
    status: "offline",
    label: "Core switch (Telnet)",
    jumpHost: null,
    proxy: null,
    env: {},
    startupSnippets: [],
    lastConnected: "1w ago",
  },
  {
    id: "h-serial-console",
    name: "serial-console",
    group: "g-edge",
    protocol: "serial",
    address: "/dev/tty.usbserial-AB0",
    port: null,
    baudRate: 115200,
    username: null,
    identity: null,
    tags: ["serial", "console"],
    status: "offline",
    label: "Serial console · 115200 8N1",
    jumpHost: null,
    proxy: null,
    env: {},
    startupSnippets: [],
    lastConnected: "never",
  },
];

const IDENTITIES = [
  {
    id: "id-deploy",
    name: "deploy-ed25519",
    type: "SSH key",
    algorithm: "ed25519",
    fingerprint: "SHA256:9X2…f0q",
    attached: 6,
    passphrase: true,
  },
  {
    id: "id-bridge",
    name: "bridge-ed25519",
    type: "SSH key",
    algorithm: "ed25519",
    fingerprint: "SHA256:Lp7…3aZ",
    attached: 1,
    passphrase: false,
  },
  {
    id: "id-db",
    name: "db-rsa",
    type: "SSH key",
    algorithm: "rsa-4096",
    fingerprint: "SHA256:2cD…8wE",
    attached: 2,
    passphrase: true,
  },
  {
    id: "id-net",
    name: "net-ed25519",
    type: "SSH key",
    algorithm: "ed25519",
    fingerprint: "SHA256:Qw1…7nK",
    attached: 1,
    passphrase: false,
  },
  {
    id: "id-cert",
    name: "prod-cert (signed)",
    type: "SSH certificate",
    algorithm: "ed25519-cert",
    fingerprint: "SHA256:Tt0…9rB",
    attached: 0,
    passphrase: false,
    expires: "2026-08-09",
  },
];

// kind: local | remote | dynamic (SOCKS)
const PORT_FORWARDS = [
  {
    id: "pf-1",
    kind: "local",
    bindHost: "127.0.0.1",
    bindPort: 5432,
    targetHost: "db-primary",
    targetPort: 5432,
    host: "bastion-jump",
    running: true,
    label: "Postgres → local",
  },
  {
    id: "pf-2",
    kind: "local",
    bindHost: "127.0.0.1",
    bindPort: 8080,
    targetHost: "stage-app-01",
    targetPort: 80,
    host: "bastion-jump",
    running: true,
    label: "Stage web → local",
  },
  {
    id: "pf-3",
    kind: "dynamic",
    bindHost: "127.0.0.1",
    bindPort: 1080,
    targetHost: "—",
    targetPort: null,
    host: "bastion-jump",
    running: false,
    label: "SOCKS proxy",
  },
  {
    id: "pf-4",
    kind: "remote",
    bindHost: "*",
    bindPort: 2222,
    targetHost: "localhost",
    targetPort: 22,
    host: "stage-worker",
    running: false,
    label: "Reverse SSH",
  },
];

// status: success | failed | connected
const HISTORY = [
  { id: "hi-1", host: "web-prod-01", protocol: "ssh", when: "2 min ago", duration: "0:48", status: "connected", user: "ubuntu" },
  { id: "hi-2", host: "db-primary", protocol: "ssh", when: "12 min ago", duration: "0:12", status: "success", user: "postgres" },
  { id: "hi-3", host: "api-prod-01", protocol: "ssh", when: "1 h ago", duration: "—", status: "failed", user: "deploy", reason: "Connection refused" },
  { id: "hi-4", host: "stage-app-01", protocol: "ssh", when: "3 h ago", duration: "5:22", status: "success", user: "ubuntu" },
  { id: "hi-5", host: "switch-core-01", protocol: "telnet", when: "yesterday", duration: "2:10", status: "success", user: "admin" },
  { id: "hi-6", host: "redis-cache-01", protocol: "ssh", when: "yesterday", duration: "—", status: "failed", user: "redis", reason: "Auth failed" },
  { id: "hi-7", host: "router-edge-01", protocol: "ssh", when: "2 d ago", duration: "8:04", status: "success", user: "admin" },
  { id: "hi-8", host: "web-prod-02", protocol: "ssh", when: "2 d ago", duration: "1:51", status: "success", user: "ubuntu" },
  { id: "hi-9", host: "db-replica-02", protocol: "ssh", when: "3 d ago", duration: "0:33", status: "success", user: "postgres" },
  { id: "hi-10", host: "api-prod-01", protocol: "ssh", when: "3 d ago", duration: "—", status: "failed", user: "deploy", reason: "Host key mismatch" },
];

// SFTP — remote tree + a folder listing for /var/www/shop
const SFTP_TREE = [
  { id: "t-root", name: "/", path: "/", depth: 0, isDir: true, expanded: true },
  { id: "t-etc", name: "etc", path: "/etc", depth: 1, isDir: true, expanded: false },
  { id: "t-var", name: "var", path: "/var", depth: 1, isDir: true, expanded: true },
  { id: "t-var-log", name: "log", path: "/var/log", depth: 2, isDir: true, expanded: false },
  { id: "t-var-www", name: "www", path: "/var/www", depth: 2, isDir: true, expanded: true },
  { id: "t-var-www-shop", name: "shop", path: "/var/www/shop", depth: 3, isDir: true, expanded: true, active: true },
  { id: "t-home", name: "home", path: "/home", depth: 1, isDir: true, expanded: false },
  { id: "t-opt", name: "opt", path: "/opt", depth: 1, isDir: true, expanded: false },
];

const SFTP_RECENT = [
  { id: "r-1", host: "web-prod-01", path: "/var/www/shop", when: "2 min ago" },
  { id: "r-2", host: "db-primary", path: "/etc/postgresql/15/main", when: "1 h ago" },
  { id: "r-3", host: "stage-app-01", path: "/srv/stage-app/current", when: "yesterday" },
  { id: "r-4", host: "bastion-jump", path: "/home/bridge/uploads", when: "2 d ago" },
];

const SFTP_FILES = [
  { id: "f-1", name: "current", path: "/var/www/shop/current", isDir: true, size: "—", modified: "Jul 24  2026", perms: "drwxr-xr-x", owner: "ubuntu" },
  { id: "f-2", name: "releases", path: "/var/www/shop/releases", isDir: true, size: "—", modified: "Jul 24  2026", perms: "drwxr-xr-x", owner: "ubuntu" },
  { id: "f-3", name: "shared", path: "/var/www/shop/shared", isDir: true, size: "—", modified: "Jul 20  2026", perms: "drwxr-xr-x", owner: "ubuntu" },
  { id: "f-4", name: ".env", path: "/var/www/shop/.env", isDir: false, size: "1.2 KB", modified: "Jul 25 09:14", perms: "-rw-------", owner: "ubuntu" },
  { id: "f-5", name: "deploy.sh", path: "/var/www/shop/deploy.sh", isDir: false, size: "4.4 KB", modified: "Jul 22  2026", perms: "-rwxr-xr-x", owner: "ubuntu" },
  { id: "f-6", name: "docker-compose.yml", path: "/var/www/shop/docker-compose.yml", isDir: false, size: "912 B", modified: "Jul 23  2026", perms: "-rw-r--r--", owner: "ubuntu" },
  { id: "f-7", name: "README.md", path: "/var/www/shop/README.md", isDir: false, size: "3.1 KB", modified: "Jul 18  2026", perms: "-rw-r--r--", owner: "ubuntu" },
  { id: "f-8", name: "nginx.conf", path: "/var/www/shop/nginx.conf", isDir: false, size: "2.0 KB", modified: "Jul 21  2026", perms: "-rw-r--r--", owner: "ubuntu" },
  { id: "f-9", name: ".gitignore", path: "/var/www/shop/.gitignore", isDir: false, size: "284 B", modified: "Jul 10  2026", perms: "-rw-r--r--", owner: "ubuntu" },
];

const SNIPPETS = [
  { id: "s-tail-log", name: "Tail nginx access log", command: "tail -f /var/log/nginx/access.log" },
  { id: "s-status", name: "Service status", command: "systemctl status gunicorn --no-pager" },
  { id: "s-pg-stat", name: "Postgres active queries", command: "SELECT * FROM pg_stat_activity WHERE state='active';" },
  { id: "s-disk", name: "Disk usage top-level", command: "du -sh /* 2>/dev/null | sort -h" },
  { id: "s-docker", name: "Docker ps", command: "docker ps --format 'table {{.Names}}\t{{.Status}}'" },
  { id: "s-listen", name: "Listening ports", command: "ss -tlnp" },
  { id: "s-cpu", name: "Top CPU processes", command: "ps aux --sort=-%cpu | head -n 12" },
  { id: "s-cert", name: "TLS cert expiry", command: "echo | openssl s_client -connect :443 2>/dev/null | openssl x509 -noout -dates" },
];

// Terminal themes — name + foreground/background for the preview card.
const THEMES = [
  { id: "th-termius-dark", name: "Termius Dark", fg: "#f2f2f2", bg: "#0b0f14" },
  { id: "th-termius-light", name: "Termius Light", fg: "#1c1d1f", bg: "#fafafa" },
  { id: "th-basic", name: "Basic", fg: "#e8e8e8", bg: "#000000" },
  { id: "th-homebrew", name: "Homebrew", fg: "#33dd33", bg: "#000000" },
  { id: "th-grass", name: "Grass", fg: "#fff700", bg: "#1a1a00" },
  { id: "th-man-page", name: "Man Page", fg: "#b4d6c4", bg: "#fef3e3" },
  { id: "th-novel", name: "Novel", fg: "#3a2a1a", bg: "#dfdbc6" },
  { id: "th-ocean", name: "Ocean", fg: "#cee1e8", bg: "#1a2638" },
  { id: "th-pro", name: "Pro", fg: "#f2f2f2", bg: "#000000" },
  { id: "th-red-sands", name: "Red Sands", fg: "#d4c9b8", bg: "#7a2424" },
  { id: "th-solarized-dark", name: "Solarized Dark", fg: "#93a1a1", bg: "#002b36" },
  { id: "th-solarized-light", name: "Solarized Light", fg: "#586e75", bg: "#fdf6e3" },
  { id: "th-silver-aerogel", name: "Silver Aerogel", fg: "#b0b8c4", bg: "#15181f" },
];

// Fonts — name + a CSS font-family stack (with monospace fallbacks).
const FONTS = [
  { id: "f-scp", name: "Source Code Pro", stack: '"Source Code Pro", ui-monospace, monospace' },
  { id: "f-operator", name: "Operator Mono", stack: '"Operator Mono", ui-monospace, monospace' },
  { id: "f-fira", name: "Fira Mono", stack: '"Fira Mono", ui-monospace, monospace' },
  { id: "f-inconsolata", name: "Inconsolata-g", stack: '"Inconsolata", ui-monospace, monospace' },
  { id: "f-anon", name: "Anonymous Pro", stack: '"Anonymous Pro", ui-monospace, monospace' },
  { id: "f-ubuntu", name: "Ubuntu Mono", stack: '"Ubuntu Mono", ui-monospace, monospace' },
  { id: "f-droid", name: "Droid Sans Mono", stack: '"Droid Sans Mono", ui-monospace, monospace' },
  { id: "f-dejavu", name: "Dejavu Sans Mono", stack: '"DejaVu Sans Mono", ui-monospace, monospace' },
  { id: "f-pt", name: "PT Mono", stack: '"PT Mono", ui-monospace, monospace' },
  { id: "f-andale", name: "Andale Mono", stack: '"Andale Mono", ui-monospace, monospace' },
  { id: "f-jet", name: "JetBrains Mono", stack: '"JetBrains Mono", ui-monospace, monospace' },
];

// Keyboard shortcuts — the platform mapping for macOS.
const SHORTCUTS = [
  { id: "k-1", group: "Tabs", action: "Switch to tab 1–9", keys: ["⌘", "1…9"] },
  { id: "k-2", group: "Tabs", action: "Next tab", keys: ["⌘", "⇧", "]"] },
  { id: "k-3", group: "Tabs", action: "Previous tab", keys: ["⌘", "⇧", "["] },
  { id: "k-4", group: "Tabs", action: "Close tab", keys: ["⌘", "W"] },
  { id: "k-5", group: "Navigation", action: "Open Servers", keys: ["⌘", "T"] },
  { id: "k-6", group: "Navigation", action: "New local terminal", keys: ["⌘", "L"] },
  { id: "k-7", group: "Navigation", action: "Port forwarding", keys: ["⌘", "P"] },
  { id: "k-8", group: "Terminal", action: "Copy / Paste / Select all", keys: ["⌘", "C / V / A"] },
  { id: "k-9", group: "Terminal", action: "Clear scrollback", keys: ["⌘", "K"] },
  { id: "k-10", group: "Terminal", action: "Search terminal", keys: ["⌘", "F"] },
  { id: "k-11", group: "Commands", action: "Command palette", keys: ["⌘", "S"] },
  { id: "k-12", group: "Commands", action: "Run command", keys: ["⌘", "⇧", "S"] },
  { id: "k-13", group: "Layout", action: "Resize left panel", keys: ["⌥", "⇧", "B"] },
  { id: "k-14", group: "AI", action: "Toggle AI mode", keys: ["⌘", "I"] },
];

const KNOWN_HOSTS = [
  { id: "kh-1", host: "bastion-jump", address: "203.0.113.10", type: "ed25519", fingerprint: "SHA256:9X2k…f0qA", trusted: true },
  { id: "kh-2", host: "db-primary", address: "10.0.2.5", type: "rsa", fingerprint: "SHA256:2cD8…8wE2", trusted: true },
  { id: "kh-3", host: "stage-app-01", address: "10.0.4.10", type: "ed25519", fingerprint: "SHA256:Lp7a…3aZ9", trusted: true },
  { id: "kh-4", host: "api-prod-01", address: "10.0.20", type: "ed25519", fingerprint: "SHA256:???", trusted: false, mismatch: true },
];

const FILE_ASSOCIATIONS = [
  { id: "fa-1", ext: ".log", app: "Console", icon: "terminal" },
  { id: "fa-2", ext: ".conf", app: "TextEdit", icon: "edit" },
  { id: "fa-3", ext: ".sql", app: "TablePlus", icon: "database" },
];

// A host-generic scripted AI turn (used when connecting to a host other than
// the web-prod-01 demo). Same shape as data.jsx's TIMELINE.
const GENERIC_TIMELINE = [
  {
    kind: "assistant",
    text: "Connected. I can run read-only diagnostics on this host on your behalf. Want me to start with a health check — load, disk, and listening ports?",
  },
  {
    kind: "exec",
    cmd: "uptime && echo '---' && df -h / && echo '---' && ss -tlnp 2>/dev/null | head -n 8",
    verdict: { allow: true },
    durationMs: 420,
    exitCode: 0,
    excerpt: 5,
    full: [
      [[" 21:09 up 14 days,  3:47,  1 user,  load average: 0.18, 0.22, 0.19", "c-green"]],
      ["---", "c-dim"],
      [["Filesystem  Size  Used Avail Use% Mounted on", "c-dim"]],
      [["/dev/vda1   39G   18G   19G  49% /", ""]],
      ["---", "c-dim"],
      [["LISTEN  0.0  0.0.0.0:22   sshd", "c-dim"]],
    ],
  },
  {
    kind: "assistant",
    text: "Host looks healthy — load is light, disk is under half, and only sshd is listening. Tell me what you'd like to investigate and I'll run it (I'll ask before anything destructive).",
  },
];

Object.assign(window, {
  INV: {
    VAULT,
    GROUPS,
    HOSTS,
    IDENTITIES,
    PORT_FORWARDS,
    HISTORY,
    SFTP_TREE,
    SFTP_FILES,
    SFTP_RECENT,
    SNIPPETS,
    THEMES,
    FONTS,
    SHORTCUTS,
    KNOWN_HOSTS,
    FILE_ASSOCIATIONS,
    GENERIC_TIMELINE,
  },
});
